http:
  routers:
    aiostreams:
      rule: "Host(`aiostreams.fewa.app`)"
      entryPoints:
        - websecure
      service: aiostreams
      tls:
        certResolver: cloudflare

    jackett:
      rule: "Host(`jackett.fewa.app`)"
      entryPoints:
        - websecure
      service: jackett
      tls:
        certResolver: cloudflare

  services:
    aiostreams:
      loadBalancer:
        servers:
          - url: http://aiostreams:3000

    jackett:
      loadBalancer:
        servers:
          - url: http://jackett:9117