encryptionsalt: v1:Joa6IYSH37k=:v1:Hh+mshDLqJoNgoVP:HiOwZUErUrA9jap9SCs8OxXbHiM6LQ==
config:
  oci:tenancyOcid:
    secure: v1:9J+pafNYsi3JEk35:xjXqD9o8KBAeKf5breK2kL35shfUjAmZNo43+Tahv/UCkq9MYv2p4Vr7kOoEBwVaot8gEd/M/cmU2Zo/iMzfhALMLH+egC9tW+8Ljm3yT8XNUWAU5p0XrBNA/0Bqyg0=
  oci:userOcid:
    secure: v1:ZPnHV7imVyvLqFas:oTFdfxz6A0ceo99obQXpT+ikt5FcBt6TS0Uf6/0MhtSLEK5DlP2GeZEYKWjFDI/32x3IgozO/3SYzony7mv41m0QP2M4jzGzmcXDjuumtVf0LdymZQOUC+APm0A=
  oci:fingerprint:
    secure: v1:N7+0tougl/+vJfo+:IMV0wxod8KE42xDvFIqwlvaN9EwYoD+ZTP3BGvnmysh7SA7yUMk+1ZpjB93rLLQOXUR4y9tpeNQp5DM/i6Xr
  oci:region: ap-melbourne-1
  oci:privateKeyPath:
    secure: v1:Skihl9yUqyNWkmyd:7TtLVKD8ZcC8FfhY8YCBzrOJF8Yu9ZzOSAFYtIa/lWmlG/TpcaINGsj2hlHNmU68CHjwIjc=
  kiran-vm-infra:sshPublicKey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFGpdJoSwTfZGU5Yb5bsGEFSOnBFeWj7QGS0qWhgv7uR kiranojha1226@gmail.com
  kiran-vm-infra:projectName: kiran-self-hosting
  kiran-vm-infra:cloudflareZoneId: 58dce5945a8941e4c38a3611af123052
