name: kiran-vm-infra
description: Oracle Cloud Infrastructure provisioning for an Always Free ARM VM
runtime:
  name: python
  options:
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: ""
