#!/usr/bin/env python3
from __future__ import annotations

import os
from pathlib import Path


def env_int(name: str) -> int:
    return int(os.environ[name])


def env_str(name: str) -> str:
    return os.environ[name]


CONSTANTS_FILE = Path(__file__).with_name("constants.py")


def render() -> str:
    return """# AUTO-GENERATED by infra/sync_constants.py from Taskfile.yml vars.
# Do not edit this file directly. Update Taskfile.yml and run `task sync` or `task init`.

# -- Project Defaults ---------------------------------------------------------
PROJECT_NAME_DEFAULT = {project_name_default!r}

# -- Resource Name Suffixes ---------------------------------------------------
SUFFIX_COMPARTMENT = {suffix_compartment!r}
SUFFIX_VCN = {suffix_vcn!r}
SUFFIX_IGW = {suffix_igw!r}
SUFFIX_RT = {suffix_rt!r}
SUFFIX_SL = {suffix_sl!r}
SUFFIX_SUBNET = {suffix_subnet!r}
SUFFIX_VM = {suffix_vm!r}
SUFFIX_VNIC = {suffix_vnic!r}

# -- Network ------------------------------------------------------------------
ANYWHERE = {anywhere!r}
VCN_CIDR = {vcn_cidr!r}
SUBNET_CIDR = {subnet_cidr!r}
SUBNET_DNS_LABEL = {subnet_dns_label!r}

# -- Ports --------------------------------------------------------------------
PORT_HTTP = {port_http}
PORT_HTTPS = {port_https}
SSH_PORT_INITIAL = {ssh_port_initial}  # allowed during bootstrap (cloud-init / first pyinfra run)
SSH_PORT_HARDENED = {ssh_port_hardened}  # sshd moves here after common role runs

# -- OCI Protocol Numbers -----------------------------------------------------
PROTO_TCP = {proto_tcp!r}
PROTO_ICMP = {proto_icmp!r}

# -- ICMP ---------------------------------------------------------------------
ICMP_TYPE_PATH_MTU = {icmp_type_path_mtu}  # path MTU discovery (required for TCP to work correctly)
ICMP_CODE_PATH_MTU = {icmp_code_path_mtu}
ICMP_TYPE_PING = {icmp_type_ping}

# -- Compute ------------------------------------------------------------------
# VM.Standard.A1.Flex -- Oracle Always Free: 4 OCPU, 24 GB RAM, up to 200 GB storage
INSTANCE_SHAPE = {instance_shape!r}
INSTANCE_OCPUS = {instance_ocpus}
INSTANCE_MEM_GB = {instance_mem_gb}

# -- OS Image -----------------------------------------------------------------
IMAGE_OS = {image_os!r}
IMAGE_OS_VERSION = {image_os_version!r}

# -- Config Defaults ----------------------------------------------------------
# bootVolumeSizeGb: (Oracle Always Free gives 200 GB total block storage across all instances)
BOOT_VOLUME_GB_DEFAULT = {boot_volume_gb_default!r}
AD_INDEX_DEFAULT = {ad_index_default!r}
""".format(
        project_name_default=env_str("PROJECT_NAME_DEFAULT"),
        suffix_compartment=env_str("SUFFIX_COMPARTMENT"),
        suffix_vcn=env_str("SUFFIX_VCN"),
        suffix_igw=env_str("SUFFIX_IGW"),
        suffix_rt=env_str("SUFFIX_RT"),
        suffix_sl=env_str("SUFFIX_SL"),
        suffix_subnet=env_str("SUFFIX_SUBNET"),
        suffix_vm=env_str("SUFFIX_VM"),
        suffix_vnic=env_str("SUFFIX_VNIC"),
        anywhere=env_str("ANYWHERE"),
        vcn_cidr=env_str("VCN_CIDR"),
        subnet_cidr=env_str("SUBNET_CIDR"),
        subnet_dns_label=env_str("SUBNET_DNS_LABEL"),
        port_http=env_int("PORT_HTTP"),
        port_https=env_int("PORT_HTTPS"),
        ssh_port_initial=env_int("SSH_PORT_INITIAL"),
        ssh_port_hardened=env_int("SSH_PORT_HARDENED"),
        proto_tcp=env_str("PROTO_TCP"),
        proto_icmp=env_str("PROTO_ICMP"),
        icmp_type_path_mtu=env_int("ICMP_TYPE_PATH_MTU"),
        icmp_code_path_mtu=env_int("ICMP_CODE_PATH_MTU"),
        icmp_type_ping=env_int("ICMP_TYPE_PING"),
        instance_shape=env_str("INSTANCE_SHAPE"),
        instance_ocpus=env_int("INSTANCE_OCPUS"),
        instance_mem_gb=env_int("INSTANCE_MEM_GB"),
        image_os=env_str("IMAGE_OS"),
        image_os_version=env_str("IMAGE_OS_VERSION"),
        boot_volume_gb_default=env_str("BOOT_VOLUME_GB_DEFAULT"),
        ad_index_default=env_str("AD_INDEX_DEFAULT"),
    )


def main() -> None:
    CONSTANTS_FILE.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
