[fewaapp]
207.211.156.85 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/kiranojha/.ssh/id_ed25519 ansible_ssh_port=22

[fewaapp:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o ServerAliveInterval=30'
